URL = "https://www.saucedemo.com/"
# Datos validos
USERNAME_1 = "standard_user"
USERNAME_2 = "locked_out_user"
USERNAME_3 = "problem_user"
USERNAME_4 = "performance_glitch_user"
USERNAME_5 = "error_user"
USERNAME_6 = "visual_user"
PASSWORD = "secret_sauce"
# Datos no validos
USERNAME_7 = "cirso_dela"
USERNAME_8 = "324346"
USERNAME_9 = "#$%$&%&"
USERNAME_10 = ""
USERNAME_11 = "e"
PASSWORD_EMPTY = ""
